### ISSUE TITLE
Accidentally logged in with gmail account.

### ISSUE THREAD

**Issue by 7imbrook** [rit-sse/scoreboard-2.0#16]
In typical click mash fashion, I click allow on oath to login with my @gmail account. redirects back to scoreboard, then says I'm not signed in. No promts. Click sign in again, oath automatically trys to use my gmail account again, no promt. Now I can't log in :(.

**Comment by kristenmills** [comment]
:+1: I'm assuming there is an option I can set to make it force prompt. I'll figure it out.

**Comment by kristenmills** [comment]
Did I/you fix this ever? @7imbrook

**Comment by 7imbrook** [comment]
I've never had a problem with it, let me test it real quick. Ok doesn't seem to have the same behavior anymore. Closing
