### ISSUE TITLE
Certain people can approve their own memberships

### ISSUE THREAD

**Issue by computermatt** [rit-sse/scoreboard-2.0#22]
Certain individuals are able to approve their own memberships. They should not be able to do this.

**Comment by kristenmills** [comment]
I don't think this is an issue. You should trust the primary officers to not be corrupt.

**Comment by djrenren** [comment]
![cabal](https://cloud.githubusercontent.com/assets/634666/11189441/15e880a0-8c5e-11e5-8126-5f31d60970d0.jpg)

**Comment by Omodi** [comment]
#rabble
