### ISSUE TITLE
Memberships by committee heads do not show up for approval

### ISSUE THREAD

**Issue by scioffi** [rit-sse/scoreboard-2.0#36]
Memberships submitted by committee heads do not appear for President's approval. President can submit memberships and approve them.

**Comment by kristenmills** [comment]
There is no notification for bad submissions on scoreboard iirc. It could be that you are submitting memberships that aren't passing the validations. Can you screenshot what you have in the fields before submitting?

**Comment by kristenmills** [comment]
@DanSwtmn @scioffi any update on this?

**Comment by DanSwtmn** [comment]
Only Kayla can't approve memberships. Everyone else can.

**Comment by 7imbrook** [comment]
Issue was a primary officer was put in the General committee, and also marked as primary. The checks for validating approvals require that the officer is not part of a committee.
