### ISSUE TITLE
BUG: Unable to "show more" after returning from detailed membership view

### ISSUE THREAD

**Issue by ShaydeNofziger** [rit-sse/scoreboard-2.0#38]
**Severity**: LOW

**Steps to reproduce:**
1. Go to https://sse.rit.edu/scoreboard
2. Click the "Memberships" link next to the google sign in button
3. Go back to the Scoreboard main page by clicking SSE Membership Tracker
4. Click "show more"

The console displays an error but I have not checked out the build so I get a generic "Minified exception occurred".

**Workaround**: reload the page and don't go to the Memberships link
**Reproducible**: every time.
**Platform**: Latest Safari version running on macOS Sierra.

**Comment by 7imbrook** [comment]
Can confirm, and reproduce

**Comment by 7imbrook** [comment]
@ShaydeNofziger check in like 10 mins to see if this is fixed

**Comment by ShaydeNofziger** [comment]
Confirmed fixed
