### ISSUE TITLE
Double listed members

### ISSUE THREAD

**Issue by lbokun** [rit-sse/scoreboard-2.0#41]
Some people have memberships under the same name and dce but in two different places. For example, there are two Dan Gude's with different membership amounts though there should be only one. Could be due to trailing spaces when entering the membership

**Comment by kristenmills** [comment]
https://sse.rit.edu/api/v1/users?perPage=96

If you scroll towards the end of that list, you'll start to see some tab characters next to DCEs. 

Action Items: 
1. The validator on node API shouldn't allow users to be created with DCEsthat don't match the pattern ^ [a-z]{2,3}\d{4}$.  I'm going to bet I set it to just [a-z]{2,3}\d{4} but will confirm later. I'll open an issue over on that side.
1. Someone needs to manually fix this. @7imbrook @DanSwtmn can one of you handle that?  Update the userDce field on the bad memberships then delete the bad users is probably the easiest. You don't even really have to delete the bad users....but probably should.

**Comment by 7imbrook** [comment]
This issue is getting handled on the node-api repo [issue 44](https://github.com/rit-sse/node-api/issues/44)

**Comment by kristenmills** [comment]
Closing this as well since we fixed it over on the node-api side.
